### PR TITLE
805 comments

### PR DESCRIPTION
**Pull request by dwalintukan**
#805 
- Added comments for every var in models
- Fixed all bad refs to `ResultHistory` and `TransactionHistory` components

### CODE REVIEW

**Comment by dwalintukan** [comment]
@amazingandyyy why is this closed? we should merge all the comments I added.

**Comment by amazingandyyy** [comment]
@dwalintukan oh! sorry!

**Comment by amazingandyyy** [comment]
I was seeing over 4000 lines of updates and think it's dulplicated somehow. a think a rebase can fix them

**Comment by amazingandyyy** [comment]
please reopen the PR, dismiss my misunderstanding.

**Comment by ippudo** [comment]
It's because of the package-lock.json

**Pull request closed without merging**
